# For available configuration options, see:
#   https://github.com/testdouble/standard
ruby_version: 2.6
fix: false               # default: false
parallel: true           # default: false
format: progress         # default: Standard::Formatter
default_ignores: false   # default: true

ignore:                  # default: []
  - '**/db/schema.rb'
  - '**/vendor/**/*'
  - '**/bin/**/*'
